import { SetMetadata } from '@nestjs/common';
import { UserType } from '@prisma/client'; // Import the enum generated by Prisma

export const ROLES_KEY = 'roles';
export const Roles = (...roles: UserType[]) => SetMetadata(ROLES_KEY, roles);